language: android
jdk: oraclejdk8
branches:
  only:
  - master
android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28
  - extra-android-m2repository
addons:
  apt:
    packages:
    - python3
  ssh_known_hosts: modos189.ru
notifications:
  email:
    on_success: change
    on_failure: always
before_script:
- openssl aes-256-cbc -K $encrypted_460819c10bef_key -iv $encrypted_460819c10bef_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- chmod 600 /tmp/deploy_rsa
- eval "$(ssh-agent -s)"
- ssh-add /tmp/deploy_rsa
- rm -rf build/local/*
- rm -rf build/mobile/*
script:
- "./build.py local"
- "./build.py mobile"
- "curl -s https://iitc.modos189.ru/deploy.sh | bash"
